version: '3'
services:
  app:
    build: myapp/.
    image: "${REGISTRY}myapp:${TAG-latest}"
    ports: 
      - "8080:8080"
  api:
    build: myapi/.
    image: "${REGISTRY}myapi:${TAG-latest}"
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://db:1433"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "123Yeah!"
      SPRING_JPA_DATABASE-PLATFORM: "org.hibernate.dialect.SQLServer2012Dialect"
  db:
    image: "microsoft/mssql-server-linux:2017-CU12"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123Yeah!"