kind: Service
apiVersion: v1
metadata:
  name: myapi
spec:
  type: ClusterIP
  selector:
    app: myapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  labels:
    app: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: <registry name>.azurecr.io/myapi:v1.0
        ports:
        - containerPort: 8080