apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "cadullmlopsaksaks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "cadullmlopsaksaks"
    spec:
      containers:
        - name: "cadullmlopsaksaks"
          image: "cadullc.azurecr.io/cadullmlopsaksaks"
          ports:
          - containerPort: 80