kind: Service
apiVersion: v1
metadata:
  name: myapi
spec:
  type: ClusterIP
  selector:
    app: myapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  labels:
    app: myapi
spec:
  replicas: {{ .Values.myapi.replicaCount }}
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: {{.Values.registry}}/myapi:{{.Values.myapi.versionTag}}
        ports:
        - containerPort: 8080
{{ if .Values.myapi.dbUrl }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: {{.Values.myapi.dbUrl}}
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        - name: SPRING_DATASOURCE_USERNAME
          value: {{.Values.myapi.dbUsername }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{.Values.myapi.dbPassword }}
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.SQLServer2012Dialect"
{{ else }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:sqlserver://db:1433"
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123Yeah!"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.SQLServer2012Dialect"
{{ end }}