on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cadullc.azurecr.io
        username: ${{ secrets.acr_cadullc_username }}
        password: ${{ secrets.acr_cadullc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/myapi" -f  "myapi/Dockerfile" -t cadullc.azurecr.io/cadullmlopsaksaks:${{ github.sha }}
        docker push cadullc.azurecr.io/cadullmlopsaksaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cadullmlopsaksaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cadullmlopsaksaks9a39 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cadullmlopsaksaks9a39`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cadullmlopsaksaks9a39
        container-registry-url: cadullc.azurecr.io
        container-registry-username: ${{ secrets.acr_cadullc_username }}
        container-registry-password: ${{ secrets.acr_cadullc_password }}
        secret-name: cadullmlopsadockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: cadullmlopsaksaks9a39
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          cadullc.azurecr.io/cadullmlopsaksaks:${{ github.sha }}
        imagepullsecrets: |
          cadullmlopsadockerauth